default_language_version:
  python: python3.11

default_stages: [commit, push]
files: ''
exclude: '^.txt$'
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
        args: [ "--maxkb=2000" ]
      - id: check-docstring-first
      - id: check-json
        exclude: ^.vscode/settings.json
      - id: check-toml
      - id: end-of-file-fixer
        exclude: 'assets/docs/pycvcqv/_build/.*|LICENSE'
      - id: trailing-whitespace
        exclude: 'assets/docs/pycvcqv/_build/.*'
      - id: debug-statements
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-ast


  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py37-plus
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort --settings-path pyproject.toml
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --config pyproject.toml
        types: [python]
        language: system


  - repo: https://github.com/pycqa/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        language_version: python3
        exclude: ^tests/
        args:
        - -s
        - B101,B603
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: ^build/
        args: [--config, setup.cfg]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint pycvcqv
        types: [python]
        language: system
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0  # or master if you're bold
    hooks:
      - id: interrogate
        args: [--quiet, --fail-under=50]
  - repo: local
    hooks:
      - id: radon-complexity
        name: radon-complexity
        entry: poetry run radon cc --total-average
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: radon-maintainability
        name: radon-maintainability
        entry: poetry run radon mi
        types: [python]
        language: system
