# This file contains values from Cookiecutter

default_context:
  project_name: "pycvcqv"
  project_description: "Coefficient of Variation (CV) and Coefficient of Quartile Variation (CQV) with Confidence Intervals (CI) "
  organization: "pycvcqv"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "MaaniBeigy"
  email: "manibeygi@gmail.com"
  version: "0.1.1"
  line_length: "88"
  create_example_template: "none"
