name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |
          pipx install poetry
          poetry self add poetry-plugin-export

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install

      - name: Run style checks
        run: |
          make check-codestyle

      - name: Run tests
        run: |
          make test
      - name: Run coverage
        run: |
          make coverage
      - name: Run safety checks
        run: |
          make check-safety
      - name: Run mypy checks
        run: |
          make mypy
      - name: Run complexity
        run: |
          make complexity
      - name: Run maintainability
        run: |
          make maintainability
      - name: Run interrogate
        run: |
          make interrogate
